### ISSUE TITLE
Move to Apache 2.0 license

### ISSUE THREAD

**Issue by schmmd** [allenai/forces#1]
To move to the Apache 2.0 license, please list the current dependencies of this project and their licenses.  Then, if we don't have any licensing conflicts we just need to update the documentation and create a [LICENSE](https://www.apache.org/licenses/LICENSE-2.0) file at the root of the project.

**Comment by roozbehm** [comment]
I get the following error when I try to update the license: 
remote: Permission to allenai/forces.git denied to roozbehm.

**Comment by schmmd** [comment]
@roozbehm try again?  Should be fixed.

**Comment by roozbehm** [comment]
Done.
